{% set name = "jupyterlab-recents" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d295fe2506e24fe7a38d8651c265033528df94a9d535b84f88e28e295017dc01

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - jupyterlab >=3.1.0,<4.0.0
    - jupyter-packaging >=0.10.0,<2.0.0
  run:
    - python >=3.7

test:
  requires:
    - jupyterlab >=3.0.0,<4.0.0
  commands:
    - jupyter labextension list 2>&1 | grep -ie "@jlab-enhanced/recents.*OK"
    - python -m jupyterlab.browser_check  # [not linux]

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-recents
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab extension that tracks recent files and directories.

extra:
  recipe-maintainers:
    - fcollonval
